name: flutter_app
description: A new Flutter project for login and dashboard.

# Versi aplikasi dan kode build
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Package tambahan (jika diperlukan), sesuaikan dengan kebutuhan proyek
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Package tambahan untuk testing
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # Daftar assets (gambar-gambar yang digunakan dalam proyek)
  assets:
    - assets/images/login_image.png
    - assets/images/avatar.png
    - assets/images/food_image.png
    - assets/images/noodle.png
    - assets/images/chicken.png
    - assets/images/french_fries.png